### ISSUE TITLE
runsvchdir does not change runlevels on a running system

### ISSUE THREAD

**Issue by bougyman** [voidlinux/void-runit#15]
Easy to see with:

[root@xena runsvdir]# ls -al
total 8
drwxr-xr-x 1 root root  64 Feb  1 10:39 .
drwxr-xr-x 1 root root 128 Feb  1 10:16 ..
lrwxrwxrwx 1 root root   7 Feb  1 10:39 current -> default
drwxr-xr-x 1 root root 264 Feb  1 10:16 default
lrwxrwxrwx 1 root root   4 Feb  1 10:19 previous -> xena
drwxr-xr-x 1 root root  14 Feb  1 10:16 single
drwxr-xr-x 1 root root 176 Feb  1 10:20 xena
[root@xena runsvdir]# ls -al /run/runit/runsvdir/current
lrwxrwxrwx 1 root root 27 Jan 20 13:18 /run/runit/runsvdir/current -> /etc/runit/runsvdir/default
[root@xena runsvdir]# runsvchdir xena
runsvchdir: xena: now current.
[root@xena runsvdir]# ls -al
total 8
drwxr-xr-x 1 root root  64 Feb  1 10:40 .
drwxr-xr-x 1 root root 128 Feb  1 10:16 ..
lrwxrwxrwx 1 root root   4 Feb  1 10:40 current -> xena
drwxr-xr-x 1 root root 264 Feb  1 10:16 default
lrwxrwxrwx 1 root root   7 Feb  1 10:39 previous -> default
drwxr-xr-x 1 root root  14 Feb  1 10:16 single
drwxr-xr-x 1 root root 176 Feb  1 10:20 xena
[root@xena runsvdir]# ls -al /run/runit/runsvdir/current
lrwxrwxrwx 1 root root 27 Jan 20 13:18 /run/runit/runsvdir/current -> /etc/runit/runsvdir/default

The symlink in /run is always pointing to 'default' so changes made by runsvchdir are never honored.

**Comment by xtraeme** [comment]
Fixed by #16
