### ISSUE TITLE
Add rsyslog as xbps package dependency

### ISSUE THREAD

**Issue by Michael-S** [voidlinux/void-runit#2]
I could be misunderstanding the configuration, but in order to restore system logging now that journalctl is no longer used, I had to setup rsyslog with runit.  I think it should be a package dependency.  (If I am incorrect, please disregard this message.)

**Comment by xtraeme** [comment]
The syslog daemon is completely optional, as the system is perfectly capable of booting and working without it. That's why I don't force anybody a specific one, currently there are three possible choices:

- metalog
- rsyslog
- socklog-void

This issue is not applicable anymore. Thanks.
