### ISSUE TITLE
`shutdown now` puts system into runlevel single (does not poweroff the computer)

### ISSUE THREAD

**Issue by jaylesworth** [voidlinux/void-runit#69]
Void's runit implementation of shutdown takes the default action to be change runlevel to single, which runs sulogin under runit supervision (so the system never powers off, unless you enter the root password and shutdown -h)

systemd's implementation of shutdown takes the default action to be poweroff. I believe this was the same on debian's pre-systemd implementation as well (sysv?)

I've modified my sulogin runit script with:

    exec init 0

after sulogin (no exec) so that runit does not get a chance to run sulogin more than once, and the system powers off if you press ^D (as sulogin suggests it will).

**Comment by dne** [comment]
I believe you're mistaken about sysvinit's default behaviour. The shutdown(8) manpage says:

> shutdown does its job by signalling the init process, asking it  to  change  the  runlevel. Runlevel  0  is  used  to halt the system, runlevel 6 is used to reboot the system, and runlevel 1 is used to put to system into a state where administrative tasks can be performed; this is the default if neither the -h or -r flag  is  given  to  shutdown.

**Comment by Gottox** [comment]
Works as expected. See `man shutdown`.
