### ISSUE TITLE
shutdown -c doesn't remove /etc/nologin

### ISSUE THREAD

**Issue by m-cz** [voidlinux/void-runit#73]
Timed `shutdown` creates `/etc/nologin`. This file should probably be removed when `shutdown` is cancelled.

**Comment by m-cz** [comment]
BTW this problem is inherited from chneukirchen/ignite#45

**Comment by chneukirchen** [comment]
This is cleaned up at `/etc/runit/core-services/99-cleanup.sh`.

**Comment by m-cz** [comment]
What I'm trying to do is
`
root# shutdown -h +1 & sleep 3; shutdown -c now
`
After the shutdown is cancelled, `/etc/nologin` is present, succesfully denying login access to non-root users.

As far as I can see `/etc/runit/core-services/99-cleanup.sh` runs only once (at stage 1), so what am I missing here?

**Comment by chneukirchen** [comment]
Does this patch make sense?

**Comment by m-cz** [comment]
Yes, thanks.
